// Generated by https://quicktype.io
//! Endpoint que lista todas las facultades de la utm junto a sus escuelas
//! http://localhost:8000/api/general/facultades


class Facultades {
  int? id;
  String? nombre;
  List<Escuela>? escuelas;
  List<Facultades?>? items;

  Facultades({
    this.id,
    this.nombre,
    this.escuelas,
  });
  Facultades.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;
    //? Por cada item que recibe los va enviando al metodo que extrae los datos del json y retorna el mapa luego los agrega a una lista de items de tipo publicacion.
    for (var item in jsonList) {
      final Facultades? facultad = new Facultades.fromJSON(item);
      items!.add(facultad);
    }
  }
  Facultades.fromJSON(Map<String, dynamic> jsonMap) {
    try {
      id = jsonMap['id'] != null ? int.parse(jsonMap['id']) : 0;
      nombre = jsonMap['nombre'] != null ? jsonMap['nombre'].toString() : '';
      escuelas = jsonMap['escuelas'] != null &&
              (jsonMap['escuelas'] as List).length > 0
          ? List.from(jsonMap['escuelas'])
              .map((element) => Escuela.fromJSON(element))
              .toSet()
              .toList()
          : <Escuela>[];
    } catch (e) {
      print(e);
    }
  }
}

class Escuela {
  int? id;
  String? nombre;

  Escuela({
    this.id,
    this.nombre,
  });

  Escuela.fromJSON(Map<String, dynamic> jsonMap) {
    try {
      id = jsonMap['id'] != null ? int.parse(jsonMap['id']) : 0;
      nombre = jsonMap['nombre'] != null ? jsonMap['nombre'].toString() : '';
    } catch (e) {
      print(e);
    }
  }
}
